grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 2
    verbose: 2

model_selection:
  module_0:
    class: GaussianNB
    module: sklearn.naive_bayes


  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 100
      min_samples_leaf: 2
    search_param_grid:
      min_samples_leaf:
      - 2
      - 4
      n_estimators:
      - 50
      - 70
      - 140